# Generated by Django 6.0.2 on 2026-02-28 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_attempted', models.IntegerField(default=0)),
                ('total_correct', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.topic')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'topic'], name='analytics_t_student_a8f1fa_idx')],
                'unique_together': {('student', 'topic')},
            },
        ),
    ]
