from django.urls import path
from .views import (
    MockSessionAnswerView,
    MockSessionCurrentSectionView,
    MockSessionNextSectionView,
    MockSessionPaletteView,
    MockSessionResultView,
    MockSessionReviewView,
    MockSessionStartView,
    MockSessionSubmitView,
    PracticeSessionResultView,
    PracticeSessionReviewView,
    PracticeSessionStartView,
    PracticeSessionSubmitView,
    PracticeTopicSessionStartView,
    StartTestView,
    SubmitTestView,
    WeakPracticeSessionStartView,
    TestHistoryView,
    TestResultView,
    WeakPracticeTestView,
)

urlpatterns = [
    path('start/', StartTestView.as_view()),
    path('submit/', SubmitTestView.as_view()),
    path('history/', TestHistoryView.as_view()),
    path('result/<int:mock_test_id>/', TestResultView.as_view()),
    path('weak-practice/', WeakPracticeTestView.as_view()),
    path('mock/start/', MockSessionStartView.as_view()),
    path('mock/answer/', MockSessionAnswerView.as_view()),
    path('mock/submit/', MockSessionSubmitView.as_view()),
    path('mock/result/<int:test_session_id>/', MockSessionResultView.as_view()),
    path('mock/review/<int:test_session_id>/', MockSessionReviewView.as_view()),
    path('mock/section/current/', MockSessionCurrentSectionView.as_view()),
    path('mock/section/next/', MockSessionNextSectionView.as_view()),
    path('mock/palette/', MockSessionPaletteView.as_view()),
    path('practice/start/', PracticeSessionStartView.as_view()),
    path('practice/topic/start/', PracticeTopicSessionStartView.as_view()),
    path('practice/submit/', PracticeSessionSubmitView.as_view()),
    path('practice/result/<int:test_session_id>/', PracticeSessionResultView.as_view()),
    path('practice/review/<int:test_session_id>/', PracticeSessionReviewView.as_view()),
    path('practice/weak/start/', WeakPracticeSessionStartView.as_view()),
]
