# Generated by Django 6.0.2 on 2026-03-01 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=255)),
                ('total_duration_sec', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='exams.exam')),
            ],
        ),
        migrations.CreateModel(
            name='PatternSectionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.PositiveIntegerField()),
                ('question_count', models.PositiveIntegerField()),
                ('section_duration_sec', models.PositiveIntegerField()),
                ('allow_section_switch', models.BooleanField(default=True)),
                ('exam_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_rules', to='exams.exampattern')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.section')),
            ],
        ),
        migrations.AddIndex(
            model_name='exampattern',
            index=models.Index(fields=['exam', 'is_active'], name='exams_examp_exam_id_2d9315_idx'),
        ),
        migrations.AddConstraint(
            model_name='exampattern',
            constraint=models.UniqueConstraint(fields=('exam', 'version'), name='unique_exam_pattern_version'),
        ),
        migrations.AddIndex(
            model_name='patternsectionrule',
            index=models.Index(fields=['exam_pattern', 'order_no'], name='exams_patte_exam_pa_a5efa8_idx'),
        ),
        migrations.AddConstraint(
            model_name='patternsectionrule',
            constraint=models.UniqueConstraint(fields=('exam_pattern', 'order_no'), name='unique_section_order_per_pattern'),
        ),
        migrations.AddConstraint(
            model_name='patternsectionrule',
            constraint=models.UniqueConstraint(fields=('exam_pattern', 'section'), name='unique_section_per_pattern'),
        ),
    ]
