# Generated by Django 6.0.2 on 2026-03-01 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exampattern_patternsectionrule_and_more'),
        ('questions', '0001_initial'),
        ('tests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('full_mock', 'Full Mock'), ('practice_section', 'Practice Section'), ('practice_topic', 'Practice Topic'), ('weak_practice', 'Weak Topic Practice')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('submitted', 'Submitted'), ('expired', 'Expired')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('total_score', models.IntegerField(default=0)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
                ('exam_pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='exams.exampattern')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionSectionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.PositiveIntegerField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('attempted_count', models.IntegerField(default=0)),
                ('correct_count', models.IntegerField(default=0)),
                ('incorrect_count', models.IntegerField(default=0)),
                ('unattempted_count', models.IntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.section')),
                ('test_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_states', to='tests.testsession')),
            ],
        ),
        migrations.CreateModel(
            name='SessionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField()),
                ('marks', models.IntegerField(default=1)),
                ('negative_marks', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.section')),
                ('test_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_questions', to='tests.testsession')),
            ],
        ),
        migrations.AddIndex(
            model_name='testsession',
            index=models.Index(fields=['student', 'status'], name='tests_tests_student_2c1153_idx'),
        ),
        migrations.AddIndex(
            model_name='testsession',
            index=models.Index(fields=['student', 'started_at'], name='tests_tests_student_3b6ff9_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionsectionstate',
            index=models.Index(fields=['test_session', 'order_no'], name='tests_sessi_test_se_af5811_idx'),
        ),
        migrations.AddConstraint(
            model_name='sessionsectionstate',
            constraint=models.UniqueConstraint(fields=('test_session', 'order_no'), name='unique_order_per_test_session'),
        ),
        migrations.AddConstraint(
            model_name='sessionsectionstate',
            constraint=models.UniqueConstraint(fields=('test_session', 'section'), name='unique_section_per_test_session'),
        ),
        migrations.AddIndex(
            model_name='sessionquestion',
            index=models.Index(fields=['test_session', 'section'], name='tests_sessi_test_se_cc76fb_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionquestion',
            index=models.Index(fields=['test_session', 'display_order'], name='tests_sessi_test_se_1f3734_idx'),
        ),
        migrations.AddConstraint(
            model_name='sessionquestion',
            constraint=models.UniqueConstraint(fields=('test_session', 'question'), name='unique_question_per_test_session'),
        ),
        migrations.AddConstraint(
            model_name='sessionquestion',
            constraint=models.UniqueConstraint(fields=('test_session', 'display_order'), name='unique_display_order_per_test_session'),
        ),
    ]
