# Generated by Django 6.0.2 on 2026-03-01 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        ('tests', '0002_testsession_sessionsectionstate_sessionquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptanswer',
            name='answered_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='attemptanswer',
            name='marked_for_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attemptanswer',
            name='test_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests.testsession'),
        ),
        migrations.AddField(
            model_name='attemptanswer',
            name='time_spent_sec',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attemptanswer',
            name='mock_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests.mocktest'),
        ),
        migrations.AddIndex(
            model_name='attemptanswer',
            index=models.Index(fields=['test_session', 'question'], name='tests_attem_test_se_ba3b2f_idx'),
        ),
    ]
