# Generated by Django 6.0.2 on 2026-03-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_attemptanswer_answered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionquestion',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionquestion',
            name='is_marked_for_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionquestion',
            name='last_visited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionquestion',
            name='seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionquestion',
            name='time_spent_sec_total',
            field=models.IntegerField(default=0),
        ),
    ]
